version: '2'
services:
  www:
    build: www/.
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
    hostname: myappserver
  db:
    build: db/.
    volumes:
      - /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: 3ad853f1abc94a67dc9ceed07547d5aa6dd5ce129611feb2
       MYSQL_DATABASE: dinerUser
    hostname: mydbserver
